# LLM Chat Gateway Configuration

# server.yml
server.httpsPort: 8443
server.enableHttp: false
server.enableHttps: true
server.serviceId: com.networknt.llmchat-gateway-1.0.0
server.enableRegistry: false

# handler.yml
handler.handlers:
  - com.networknt.websocket.router.WebSocketRouterHandler@router
  - com.networknt.resource.PathResourceHandler@resource

handler.chains:
  default:
    - router

handler.paths:
  - path: '/'
    method: 'GET'
    exec:
      - resource
  - path: '/chat'
    method: 'GET'
    exec:
      - default

# websocket-router.yml
websocket-router.enabled: true
websocket-router.pathPrefixService:
  /chat: com.networknt.llmchat-1.0.0

# service.yml
service.singletons:
  - com.networknt.registry.URL:
    - com.networknt.registry.URLImpl
  - com.networknt.registry.Registry:
    - com.networknt.registry.support.DirectRegistry
  - com.networknt.balance.LoadBalance:
    - com.networknt.balance.RoundRobinLoadBalance
  - com.networknt.cluster.Cluster:
    - com.networknt.cluster.LightCluster


# path-resource.yaml
path-resource.path: /
path-resource.base: /home/steve/networknt/light-gateway/config/llmchat-gateway/public

# direct-registry.yml
direct-registry:
  com.networknt.llmchat-1.0.0:
    - http://localhost:8080
