# server.yml
server.httpsPort: 8443
server.httpPort: 8080
server.enableHttp: true
server.enableHttps: true
server.serviceId: com.networknt.mcp-router-1.0.0
server.enableRegistry: false

# mcp-router.yml
mcp-router.enabled: true
mcp-router.path: /mcp
mcp-router.tools:
  - name: listPets
    description: List all pets
    host: https://localhost:9443
    path: /v1/pets
    method: GET
  - name: createPet
    description: Create a pet
    host: https://localhost:9443
    path: /v1/pets
    method: POST
    inputSchema:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
      required:
        - id
        - name

# client.yml
client.verifyHostname: false
client.timeout: 3000

# handler.yml
handler.handlers:
  - com.networknt.cors.CorsHttpHandler@cors
  - com.networknt.mcp.McpHandler@mcp
  - com.networknt.exception.ExceptionHandler@exception

handler.paths:
  - path: '/mcp'
    method: 'GET'
    exec:
      - cors
      - exception
      - mcp
  - path: '/mcp'
    method: 'POST'
    exec:
      - cors
      - exception
      - mcp

  - path: '/mcp'
    method: 'OPTIONS'
    exec:
      - cors

# cors.yml
cors.enabled: true
cors.allowedOrigins:
  - http://localhost:8080
  - http://0.0.0.0:6274
cors.allowedMethods:
  - GET
  - POST
  - PUT
  - DELETE
  - OPTIONS

# service.yml
service.singletons:
  - com.networknt.registry.URL:
    - com.networknt.registry.URLImpl
  - com.networknt.registry.Registry:
    - com.networknt.registry.support.DirectRegistry
  - com.networknt.balance.LoadBalance:
    - com.networknt.balance.RoundRobinLoadBalance
  - com.networknt.cluster.Cluster:
    - com.networknt.cluster.LightCluster
